//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PortalModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class PortalEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“PortalEntities”部分中的连接字符串初始化新 PortalEntities 对象。
        /// </summary>
        public PortalEntities() : base("name=PortalEntities", "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PortalEntities 对象。
        /// </summary>
        public PortalEntities(string connectionString) : base(connectionString, "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PortalEntities 对象。
        /// </summary>
        public PortalEntities(EntityConnection connection) : base(connection, "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalContent> PortalContent
        {
            get
            {
                if ((_PortalContent == null))
                {
                    _PortalContent = base.CreateObjectSet<PortalContent>("PortalContent");
                }
                return _PortalContent;
            }
        }
        private ObjectSet<PortalContent> _PortalContent;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalDocument> PortalDocument
        {
            get
            {
                if ((_PortalDocument == null))
                {
                    _PortalDocument = base.CreateObjectSet<PortalDocument>("PortalDocument");
                }
                return _PortalDocument;
            }
        }
        private ObjectSet<PortalDocument> _PortalDocument;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalManager> PortalManager
        {
            get
            {
                if ((_PortalManager == null))
                {
                    _PortalManager = base.CreateObjectSet<PortalManager>("PortalManager");
                }
                return _PortalManager;
            }
        }
        private ObjectSet<PortalManager> _PortalManager;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalUser> PortalUser
        {
            get
            {
                if ((_PortalUser == null))
                {
                    _PortalUser = base.CreateObjectSet<PortalUser>("PortalUser");
                }
                return _PortalUser;
            }
        }
        private ObjectSet<PortalUser> _PortalUser;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalMenu> PortalMenu
        {
            get
            {
                if ((_PortalMenu == null))
                {
                    _PortalMenu = base.CreateObjectSet<PortalMenu>("PortalMenu");
                }
                return _PortalMenu;
            }
        }
        private ObjectSet<PortalMenu> _PortalMenu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysConfig> SysConfig
        {
            get
            {
                if ((_SysConfig == null))
                {
                    _SysConfig = base.CreateObjectSet<SysConfig>("SysConfig");
                }
                return _SysConfig;
            }
        }
        private ObjectSet<SysConfig> _SysConfig;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalCategory> PortalCategory
        {
            get
            {
                if ((_PortalCategory == null))
                {
                    _PortalCategory = base.CreateObjectSet<PortalCategory>("PortalCategory");
                }
                return _PortalCategory;
            }
        }
        private ObjectSet<PortalCategory> _PortalCategory;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 PortalContent EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPortalContent(PortalContent portalContent)
        {
            base.AddObject("PortalContent", portalContent);
        }
    
        /// <summary>
        /// 用于向 PortalDocument EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPortalDocument(PortalDocument portalDocument)
        {
            base.AddObject("PortalDocument", portalDocument);
        }
    
        /// <summary>
        /// 用于向 PortalManager EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPortalManager(PortalManager portalManager)
        {
            base.AddObject("PortalManager", portalManager);
        }
    
        /// <summary>
        /// 用于向 PortalUser EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPortalUser(PortalUser portalUser)
        {
            base.AddObject("PortalUser", portalUser);
        }
    
        /// <summary>
        /// 用于向 PortalMenu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPortalMenu(PortalMenu portalMenu)
        {
            base.AddObject("PortalMenu", portalMenu);
        }
    
        /// <summary>
        /// 用于向 SysConfig EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysConfig(SysConfig sysConfig)
        {
            base.AddObject("SysConfig", sysConfig);
        }
    
        /// <summary>
        /// 用于向 PortalCategory EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPortalCategory(PortalCategory portalCategory)
        {
            base.AddObject("PortalCategory", portalCategory);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="PortalCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalCategory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PortalCategory 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static PortalCategory CreatePortalCategory(global::System.Int32 id)
        {
            PortalCategory portalCategory = new PortalCategory();
            portalCategory.ID = id;
            return portalCategory;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int32> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Seq
        {
            get
            {
                return _Seq;
            }
            set
            {
                OnSeqChanging(value);
                ReportPropertyChanging("Seq");
                _Seq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seq");
                OnSeqChanged();
            }
        }
        private Nullable<global::System.Int32> _Seq;
        partial void OnSeqChanging(Nullable<global::System.Int32> value);
        partial void OnSeqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Boolean> _State;
        partial void OnStateChanging(Nullable<global::System.Boolean> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="PortalContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalContent : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PortalContent 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="categoryID">CategoryID 属性的初始值。</param>
        /// <param name="description">Description 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        /// <param name="uRL">URL 属性的初始值。</param>
        /// <param name="state">State 属性的初始值。</param>
        /// <param name="createDate">CreateDate 属性的初始值。</param>
        /// <param name="extend1">Extend1 属性的初始值。</param>
        /// <param name="extend2">Extend2 属性的初始值。</param>
        /// <param name="extend3">Extend3 属性的初始值。</param>
        public static PortalContent CreatePortalContent(global::System.Int32 id, global::System.String name, global::System.Int32 categoryID, global::System.String description, global::System.Int32 type, global::System.String uRL, global::System.Boolean state, global::System.DateTime createDate, global::System.String extend1, global::System.String extend2, global::System.String extend3)
        {
            PortalContent portalContent = new PortalContent();
            portalContent.ID = id;
            portalContent.Name = name;
            portalContent.CategoryID = categoryID;
            portalContent.Description = description;
            portalContent.Type = type;
            portalContent.URL = uRL;
            portalContent.State = state;
            portalContent.CreateDate = createDate;
            portalContent.Extend1 = extend1;
            portalContent.Extend2 = extend2;
            portalContent.Extend3 = extend3;
            return portalContent;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if (_Description != value)
                {
                    OnDescriptionChanging(value);
                    ReportPropertyChanging("Description");
                    _Description = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                if (_Type != value)
                {
                    OnTypeChanging(value);
                    ReportPropertyChanging("Type");
                    _Type = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Type");
                    OnTypeChanged();
                }
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL2
        {
            get
            {
                return _ImageURL2;
            }
            set
            {
                OnImageURL2Changing(value);
                ReportPropertyChanging("ImageURL2");
                _ImageURL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL2");
                OnImageURL2Changed();
            }
        }
        private global::System.String _ImageURL2;
        partial void OnImageURL2Changing(global::System.String value);
        partial void OnImageURL2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                if (_URL != value)
                {
                    OnURLChanging(value);
                    ReportPropertyChanging("URL");
                    _URL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("URL");
                    OnURLChanged();
                }
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.Boolean _State;
        partial void OnStateChanging(global::System.Boolean value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Extend1
        {
            get
            {
                return _Extend1;
            }
            set
            {
                if (_Extend1 != value)
                {
                    OnExtend1Changing(value);
                    ReportPropertyChanging("Extend1");
                    _Extend1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Extend1");
                    OnExtend1Changed();
                }
            }
        }
        private global::System.String _Extend1;
        partial void OnExtend1Changing(global::System.String value);
        partial void OnExtend1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Extend2
        {
            get
            {
                return _Extend2;
            }
            set
            {
                if (_Extend2 != value)
                {
                    OnExtend2Changing(value);
                    ReportPropertyChanging("Extend2");
                    _Extend2 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Extend2");
                    OnExtend2Changed();
                }
            }
        }
        private global::System.String _Extend2;
        partial void OnExtend2Changing(global::System.String value);
        partial void OnExtend2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Extend3
        {
            get
            {
                return _Extend3;
            }
            set
            {
                if (_Extend3 != value)
                {
                    OnExtend3Changing(value);
                    ReportPropertyChanging("Extend3");
                    _Extend3 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Extend3");
                    OnExtend3Changed();
                }
            }
        }
        private global::System.String _Extend3;
        partial void OnExtend3Changing(global::System.String value);
        partial void OnExtend3Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="PortalDocument")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalDocument : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PortalDocument 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="portalMenuID">PortalMenuID 属性的初始值。</param>
        /// <param name="portalMenuCode">PortalMenuCode 属性的初始值。</param>
        /// <param name="uRL">URL 属性的初始值。</param>
        /// <param name="description">Description 属性的初始值。</param>
        /// <param name="imageURL">ImageURL 属性的初始值。</param>
        /// <param name="seq">Seq 属性的初始值。</param>
        /// <param name="state">State 属性的初始值。</param>
        /// <param name="createDate">CreateDate 属性的初始值。</param>
        public static PortalDocument CreatePortalDocument(global::System.Int32 id, global::System.String name, global::System.Int32 portalMenuID, global::System.String portalMenuCode, global::System.String uRL, global::System.String description, global::System.String imageURL, global::System.Int32 seq, global::System.Boolean state, global::System.DateTime createDate)
        {
            PortalDocument portalDocument = new PortalDocument();
            portalDocument.ID = id;
            portalDocument.Name = name;
            portalDocument.PortalMenuID = portalMenuID;
            portalDocument.PortalMenuCode = portalMenuCode;
            portalDocument.URL = uRL;
            portalDocument.Description = description;
            portalDocument.ImageURL = imageURL;
            portalDocument.Seq = seq;
            portalDocument.State = state;
            portalDocument.CreateDate = createDate;
            return portalDocument;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PortalMenuID
        {
            get
            {
                return _PortalMenuID;
            }
            set
            {
                if (_PortalMenuID != value)
                {
                    OnPortalMenuIDChanging(value);
                    ReportPropertyChanging("PortalMenuID");
                    _PortalMenuID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PortalMenuID");
                    OnPortalMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _PortalMenuID;
        partial void OnPortalMenuIDChanging(global::System.Int32 value);
        partial void OnPortalMenuIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PortalMenuCode
        {
            get
            {
                return _PortalMenuCode;
            }
            set
            {
                if (_PortalMenuCode != value)
                {
                    OnPortalMenuCodeChanging(value);
                    ReportPropertyChanging("PortalMenuCode");
                    _PortalMenuCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PortalMenuCode");
                    OnPortalMenuCodeChanged();
                }
            }
        }
        private global::System.String _PortalMenuCode;
        partial void OnPortalMenuCodeChanging(global::System.String value);
        partial void OnPortalMenuCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                if (_URL != value)
                {
                    OnURLChanging(value);
                    ReportPropertyChanging("URL");
                    _URL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("URL");
                    OnURLChanged();
                }
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if (_Description != value)
                {
                    OnDescriptionChanging(value);
                    ReportPropertyChanging("Description");
                    _Description = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                if (_ImageURL != value)
                {
                    OnImageURLChanging(value);
                    ReportPropertyChanging("ImageURL");
                    _ImageURL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ImageURL");
                    OnImageURLChanged();
                }
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL2
        {
            get
            {
                return _ImageURL2;
            }
            set
            {
                OnImageURL2Changing(value);
                ReportPropertyChanging("ImageURL2");
                _ImageURL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL2");
                OnImageURL2Changed();
            }
        }
        private global::System.String _ImageURL2;
        partial void OnImageURL2Changing(global::System.String value);
        partial void OnImageURL2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seq
        {
            get
            {
                return _Seq;
            }
            set
            {
                if (_Seq != value)
                {
                    OnSeqChanging(value);
                    ReportPropertyChanging("Seq");
                    _Seq = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Seq");
                    OnSeqChanged();
                }
            }
        }
        private global::System.Int32 _Seq;
        partial void OnSeqChanging(global::System.Int32 value);
        partial void OnSeqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.Boolean _State;
        partial void OnStateChanging(global::System.Boolean value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extend1
        {
            get
            {
                return _Extend1;
            }
            set
            {
                OnExtend1Changing(value);
                ReportPropertyChanging("Extend1");
                _Extend1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extend1");
                OnExtend1Changed();
            }
        }
        private global::System.String _Extend1;
        partial void OnExtend1Changing(global::System.String value);
        partial void OnExtend1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extend2
        {
            get
            {
                return _Extend2;
            }
            set
            {
                OnExtend2Changing(value);
                ReportPropertyChanging("Extend2");
                _Extend2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extend2");
                OnExtend2Changed();
            }
        }
        private global::System.String _Extend2;
        partial void OnExtend2Changing(global::System.String value);
        partial void OnExtend2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extend3
        {
            get
            {
                return _Extend3;
            }
            set
            {
                OnExtend3Changing(value);
                ReportPropertyChanging("Extend3");
                _Extend3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extend3");
                OnExtend3Changed();
            }
        }
        private global::System.String _Extend3;
        partial void OnExtend3Changing(global::System.String value);
        partial void OnExtend3Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="PortalManager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalManager : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PortalManager 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="displayName">DisplayName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="state">State 属性的初始值。</param>
        /// <param name="createDate">CreateDate 属性的初始值。</param>
        public static PortalManager CreatePortalManager(global::System.Int32 id, global::System.String userName, global::System.String displayName, global::System.String password, global::System.Boolean state, global::System.DateTime createDate)
        {
            PortalManager portalManager = new PortalManager();
            portalManager.ID = id;
            portalManager.UserName = userName;
            portalManager.DisplayName = displayName;
            portalManager.Password = password;
            portalManager.State = state;
            portalManager.CreateDate = createDate;
            return portalManager;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                if (_DisplayName != value)
                {
                    OnDisplayNameChanging(value);
                    ReportPropertyChanging("DisplayName");
                    _DisplayName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DisplayName");
                    OnDisplayNameChanged();
                }
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                if (_Password != value)
                {
                    OnPasswordChanging(value);
                    ReportPropertyChanging("Password");
                    _Password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Password");
                    OnPasswordChanged();
                }
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.Boolean _State;
        partial void OnStateChanging(global::System.Boolean value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="PortalMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalMenu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PortalMenu 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        /// <param name="parentID">ParentID 属性的初始值。</param>
        /// <param name="parentCode">ParentCode 属性的初始值。</param>
        /// <param name="uRL">URL 属性的初始值。</param>
        /// <param name="imageUrl">ImageUrl 属性的初始值。</param>
        /// <param name="seq">Seq 属性的初始值。</param>
        /// <param name="state">State 属性的初始值。</param>
        /// <param name="createDate">CreateDate 属性的初始值。</param>
        public static PortalMenu CreatePortalMenu(global::System.Int32 id, global::System.String name, global::System.String code, global::System.Int32 type, global::System.Int32 parentID, global::System.String parentCode, global::System.String uRL, global::System.String imageUrl, global::System.Int32 seq, global::System.Boolean state, global::System.DateTime createDate)
        {
            PortalMenu portalMenu = new PortalMenu();
            portalMenu.ID = id;
            portalMenu.Name = name;
            portalMenu.Code = code;
            portalMenu.Type = type;
            portalMenu.ParentID = parentID;
            portalMenu.ParentCode = parentCode;
            portalMenu.URL = uRL;
            portalMenu.ImageUrl = imageUrl;
            portalMenu.Seq = seq;
            portalMenu.State = state;
            portalMenu.CreateDate = createDate;
            return portalMenu;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                if (_Type != value)
                {
                    OnTypeChanging(value);
                    ReportPropertyChanging("Type");
                    _Type = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Type");
                    OnTypeChanged();
                }
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                if (_ParentID != value)
                {
                    OnParentIDChanging(value);
                    ReportPropertyChanging("ParentID");
                    _ParentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ParentID");
                    OnParentIDChanged();
                }
            }
        }
        private global::System.Int32 _ParentID;
        partial void OnParentIDChanging(global::System.Int32 value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParentCode
        {
            get
            {
                return _ParentCode;
            }
            set
            {
                if (_ParentCode != value)
                {
                    OnParentCodeChanging(value);
                    ReportPropertyChanging("ParentCode");
                    _ParentCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ParentCode");
                    OnParentCodeChanged();
                }
            }
        }
        private global::System.String _ParentCode;
        partial void OnParentCodeChanging(global::System.String value);
        partial void OnParentCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                if (_URL != value)
                {
                    OnURLChanging(value);
                    ReportPropertyChanging("URL");
                    _URL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("URL");
                    OnURLChanged();
                }
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                if (_ImageUrl != value)
                {
                    OnImageUrlChanging(value);
                    ReportPropertyChanging("ImageUrl");
                    _ImageUrl = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ImageUrl");
                    OnImageUrlChanged();
                }
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seq
        {
            get
            {
                return _Seq;
            }
            set
            {
                if (_Seq != value)
                {
                    OnSeqChanging(value);
                    ReportPropertyChanging("Seq");
                    _Seq = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Seq");
                    OnSeqChanged();
                }
            }
        }
        private global::System.Int32 _Seq;
        partial void OnSeqChanging(global::System.Int32 value);
        partial void OnSeqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.Boolean _State;
        partial void OnStateChanging(global::System.Boolean value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="PortalUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalUser : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PortalUser 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="displayName">DisplayName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="state">State 属性的初始值。</param>
        /// <param name="createDate">CreateDate 属性的初始值。</param>
        public static PortalUser CreatePortalUser(global::System.Int32 id, global::System.String userName, global::System.String displayName, global::System.String password, global::System.Boolean state, global::System.DateTime createDate)
        {
            PortalUser portalUser = new PortalUser();
            portalUser.ID = id;
            portalUser.UserName = userName;
            portalUser.DisplayName = displayName;
            portalUser.Password = password;
            portalUser.State = state;
            portalUser.CreateDate = createDate;
            return portalUser;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                if (_DisplayName != value)
                {
                    OnDisplayNameChanging(value);
                    ReportPropertyChanging("DisplayName");
                    _DisplayName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DisplayName");
                    OnDisplayNameChanged();
                }
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                if (_Password != value)
                {
                    OnPasswordChanging(value);
                    ReportPropertyChanging("Password");
                    _Password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Password");
                    OnPasswordChanged();
                }
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.Boolean _State;
        partial void OnStateChanging(global::System.Boolean value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="SysConfig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysConfig : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysConfig 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="value">Value 属性的初始值。</param>
        public static SysConfig CreateSysConfig(global::System.Int32 id, global::System.String name, global::System.String code, global::System.String value)
        {
            SysConfig sysConfig = new SysConfig();
            sysConfig.ID = id;
            sysConfig.Name = name;
            sysConfig.Code = code;
            sysConfig.Value = value;
            return sysConfig;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                if (_Value != value)
                {
                    OnValueChanging(value);
                    ReportPropertyChanging("Value");
                    _Value = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Value");
                    OnValueChanged();
                }
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }

    #endregion

    
}
